-- CRIA BANCO DE DADOS
DROP DATABASE OFICINA;
CREATE DATABASE OFICINA;
USE OFICINA;
--
-- CRIA TABELA FORNECEDOR
CREATE TABLE IF NOT EXISTS FORNECEDOR (
  ID INT NOT NULL AUTO_INCREMENT,
  RAZAO_SOCIAL VARCHAR(250) NOT NULL,
  CNPJ CHAR(15) NOT NULL,
  ENDERECO VARCHAR(250) NOT NULL,
  PRIMARY KEY (ID));
ALTER TABLE FORNECEDOR AUTO_INCREMENT = 1;
--
-- CRIA TABELA LOCAL ESTOQUE
CREATE TABLE IF NOT EXISTS LOCAL_ESTOQUE (
  ID INT NOT NULL AUTO_INCREMENT,
  DESCRICAO VARCHAR(250) NOT NULL,
  PRIMARY KEY (ID));
ALTER TABLE LOCAL_ESTOQUE AUTO_INCREMENT = 1;
--
-- CRIA TABELA SERVICO
CREATE TABLE IF NOT EXISTS SERVICO (
  ID INT NOT NULL AUTO_INCREMENT,
  DESCRICAO VARCHAR(250) NOT NULL,
  VALOR FLOAT NOT NULL,
  PRIMARY KEY (ID));
ALTER TABLE SERVICO AUTO_INCREMENT = 1;
--
-- CRIA TABELA MECANICO
CREATE TABLE IF NOT EXISTS MECANICO (
  ID INT NOT NULL AUTO_INCREMENT,
  NOME VARCHAR(45) NOT NULL,
  SALARIO FLOAT NOT NULL,
  DATA_ADMISSAO DATE NOT NULL,
  PRIMARY KEY (ID));
ALTER TABLE MECANICO AUTO_INCREMENT = 1;
--
-- CRIA TABELA CLIENTE
CREATE TABLE IF NOT EXISTS CLIENTE (
  ID INT NOT NULL AUTO_INCREMENT,
  NOME VARCHAR(45) NOT NULL,
  SOBRENOME VARCHAR(45) NOT NULL,
  ENDERECO VARCHAR(250) NULL,
  FIS_JUR ENUM('F', 'J') NOT NULL,
  CPF CHAR(11) NULL,
  CNPJ CHAR(15) NULL,
  PRIMARY KEY (ID));
ALTER TABLE CLIENTE AUTO_INCREMENT = 1;
--
-- CRIA TABELA PECA
CREATE TABLE IF NOT EXISTS PECA (
  ID INT NOT NULL AUTO_INCREMENT,
  DESCRICAO VARCHAR(250) NOT NULL,
  FORNECEDOR_ID INT NOT NULL,
  VALOR FLOAT NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT PECA_FK0 FOREIGN KEY (FORNECEDOR_ID) REFERENCES FORNECEDOR (ID));
ALTER TABLE PECA AUTO_INCREMENT = 1;
--
-- CRIA TABELA ESTOQUE
CREATE TABLE IF NOT EXISTS ESTOQUE (
  ID INT NOT NULL AUTO_INCREMENT,
  LOCAL_ESTOQUE_ID INT NOT NULL,
  PECA_ID INT NOT NULL,
  QUANTIDADE FLOAT NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT ESTOQUE_FK0 FOREIGN KEY (PECA_ID) REFERENCES PECA(ID),
  CONSTRAINT ESTOQUE_FK1 FOREIGN KEY (LOCAL_ESTOQUE_ID) REFERENCES LOCAL_ESTOQUE(ID));
ALTER TABLE ESTOQUE AUTO_INCREMENT = 1;
--
-- CRIA TABELA PEDIDO
CREATE TABLE IF NOT EXISTS PEDIDO (
  ID INT NOT NULL AUTO_INCREMENT,
  NUMERO INT NOT NULL,
  CLIENTE_ID INT NOT NULL,
  MECANICO_ID INT NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT PEDIDO_FK0 FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE (ID),
  CONSTRAINT PEDIDO_FK1 FOREIGN KEY (MECANICO_ID) REFERENCES MECANICO (ID));
ALTER TABLE PEDIDO AUTO_INCREMENT = 1;
--
-- CRIA TABELA PEDIDO ITEM
CREATE TABLE IF NOT EXISTS PEDIDO_ITEM (
  ID INT NOT NULL AUTO_INCREMENT,
  PEDIDO_ID INT NOT NULL,
  PECA_ID INT NOT NULL,
  SERVICO_ID INT NOT NULL,
  QUANTIDADE INT NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT PEDIDO_ITEM_FK0 FOREIGN KEY (PECA_ID) REFERENCES PECA(ID),
  CONSTRAINT PEDIDO_ITEM_FK1 FOREIGN KEY (PEDIDO_ID) REFERENCES PEDIDO (ID),
  CONSTRAINT PEDIDO_ITEM_FK2 FOREIGN KEY (SERVICO_ID) REFERENCES SERVICO (ID));
ALTER TABLE PEDIDO_ITEM AUTO_INCREMENT = 1;
